import React, { FC } from 'react';
import { ISvgProps } from '../../../types';

const Svg: FC<ISvgProps> = ({ color }) => (
  <svg viewBox="0 0 210 210" version="1.1" xmlns="http://www.w3.org/2000/svg">
    <title>prettier-icon-light</title>
    <desc>Created with sketchtool.</desc>
    <defs />
    <g id="key" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
      <g id="prettier-icon-light">
        <g id="Icon-(Light)">
          <g id="line-11" transform="translate(0.000000, 200.000000)">
            <rect
              id="line-11-dash-3"
              fill="#CFD4D7"
              opacity="0.5"
              x="150"
              y="0"
              width="60"
              height="10"
              rx="5"
            />
            <rect
              id="line-11-dash-2"
              fill="#CFD4D7"
              opacity="0.5"
              x="70"
              y="0"
              width="70"
              height="10"
              rx="5"
            />
            <rect
              id="line-11-dash-1"
              fill={color}
              x="0"
              y="0"
              width="60"
              height="10"
              rx="5"
            />
          </g>
          <g id="line-10" transform="translate(0.000000, 180.000000)">
            <rect
              id="line-10-dash-5"
              fill="#CFD4D7"
              opacity="0.5"
              x="160"
              y="0"
              width="50"
              height="10"
              rx="5"
            />
            <rect
              id="line-10-dash-4"
              fill="#CFD4D7"
              opacity="0.5"
              x="130"
              y="0"
              width="20"
              height="10"
              rx="5"
            />
            <rect
              id="line-10-dash-3"
              fill="#CFD4D7"
              opacity="0.5"
              x="70"
              y="0"
              width="50"
              height="10"
              rx="5"
            />
            <rect
              id="line-10-dash-2"
              fill="#222"
              x="40"
              y="0"
              width="20"
              height="10"
              rx="5"
            />
            <rect
              id="line-10-dash-1"
              fill={color}
              x="0"
              y="0"
              width="30"
              height="10"
              rx="5"
            />
          </g>
          <g id="line-9" transform="translate(0.000000, 160.000000)">
            <rect
              id="line-9-dash-3"
              fill="#CFD4D7"
              opacity="0.5"
              x="110"
              y="0"
              width="100"
              height="10"
              rx="5"
            />
            <rect
              id="line-9-dash-2"
              fill="#CFD4D7"
              opacity="0.5"
              x="70"
              y="0"
              width="30"
              height="10"
              rx="5"
            />
            <rect
              id="line-9-dash-1"
              fill="#222"
              x="0"
              y="0"
              width="60"
              height="10"
              rx="5"
            />
          </g>
          <g id="line-8" transform="translate(0.000000, 140.000000)">
            <rect
              id="line-8-dash-4"
              fill="#CFD4D7"
              opacity="0.5"
              x="180"
              y="0"
              width="30"
              height="10"
              rx="5"
            />
            <rect
              id="line-8-dash-3"
              fill="#CFD4D7"
              opacity="0.5"
              x="140"
              y="0"
              width="30"
              height="10"
              rx="5"
            />
            <rect
              id="line-8-dash-2"
              fill="#222"
              x="30"
              y="0"
              width="100"
              height="10"
              rx="5"
            />
            <rect
              id="line-8-dash-1"
              fill="#222"
              x="0"
              y="0"
              width="20"
              height="10"
              rx="5"
            />
          </g>
          <g id="line-7" transform="translate(0.000000, 120.000000)">
            <rect
              id="line-7-dash-4"
              fill="#CFD4D7"
              opacity="0.5"
              x="170"
              y="0"
              width="40"
              height="10"
              rx="5"
            />
            <rect
              id="line-7-dash-3"
              fill="#222"
              x="120"
              y="0"
              width="40"
              height="10"
              rx="5"
            />
            <rect
              id="line-7-dash-2"
              fill={color}
              x="60"
              y="0"
              width="50"
              height="10"
              rx="5"
            />
            <rect
              id="line-7-dash-1"
              fill={color}
              x="0"
              y="0"
              width="50"
              height="10"
              rx="5"
            />
          </g>
          <g id="line-6" transform="translate(0.000000, 100.000000)">
            <rect
              id="line-6-dash-4"
              fill="#CFD4D7"
              opacity="0.5"
              x="180"
              y="0"
              width="30"
              height="10"
              rx="5"
            />
            <rect
              id="line-6-dash-3"
              fill={color}
              x="80"
              y="0"
              width="90"
              height="10"
              rx="5"
            />
            <rect
              id="line-6-dash-2"
              fill="#222"
              x="30"
              y="0"
              width="40"
              height="10"
              rx="5"
            />
            <rect
              id="line-6-dash-1"
              fill={color}
              x="0"
              y="0"
              width="20"
              height="10"
              rx="5"
            />
          </g>
          <g id="line-5" transform="translate(0.000000, 80.000000)">
            <rect
              id="line-5-dash-4"
              fill="#CFD4D7"
              opacity="0.5"
              x="190"
              y="0"
              width="20"
              height="10"
              rx="5"
            />
            <rect
              id="line-5-dash-3"
              fill="#222"
              x="120"
              y="0"
              width="60"
              height="10"
              rx="5"
            />
            <rect
              id="line-5-dash-2"
              fill="#CFD4D7"
              opacity="0.5"
              x="70"
              y="0"
              width="40"
              height="10"
              rx="5"
            />
            <rect
              id="line-5-dash-1"
              fill="#222"
              x="0"
              y="0"
              width="60"
              height="10"
              rx="5"
            />
          </g>
          <g id="line-4" transform="translate(0.000000, 60.000000)">
            <rect
              id="line-4-dash-5"
              fill="#CFD4D7"
              opacity="0.5"
              x="190"
              y="0"
              width="20"
              height="10"
              rx="5"
            />
            <rect
              id="line-4-dash-4"
              fill={color}
              x="120"
              y="0"
              width="60"
              height="10"
              rx="5"
            />
            <rect
              id="line-4-dash-3"
              fill="#CFD4D7"
              opacity="0.5"
              x="70"
              y="0"
              width="40"
              height="10"
              rx="5"
            />
            <rect
              id="line-4-dash-2"
              fill={color}
              x="40"
              y="0"
              width="20"
              height="10"
              rx="5"
            />
            <rect
              id="line-4-dash-1"
              fill="#222"
              x="0"
              y="0"
              width="30"
              height="10"
              rx="5"
            />
          </g>
          <g id="line-3" transform="translate(0.000000, 40.000000)">
            <rect
              id="line-3-dash-4"
              fill="#CFD4D7"
              opacity="0.5"
              x="180"
              y="0"
              width="30"
              height="10"
              rx="5"
            />
            <rect
              id="line-3-dash-3"
              fill={color}
              x="150"
              y="0"
              width="20"
              height="10"
              rx="5"
            />
            <rect
              id="line-3-dash-2"
              fill="#222"
              x="90"
              y="0"
              width="50"
              height="10"
              rx="5"
            />
            <rect
              id="line-3-dash-1"
              fill={color}
              x="0"
              y="0"
              width="80"
              height="10"
              rx="5"
            />
          </g>
          <g id="line-2" transform="translate(0.000000, 20.000000)">
            <rect
              id="line-2-dash-3"
              fill="#CFD4D7"
              opacity="0.5"
              x="170"
              y="0"
              width="40"
              height="10"
              rx="5"
            />
            <rect
              id="line-2-dash-2"
              fill="#222"
              x="50"
              y="0"
              width="110"
              height="10"
              rx="5"
            />
            <rect
              id="line-2-dash-1"
              fill={color}
              x="0"
              y="0"
              width="40"
              height="10"
              rx="5"
            />
          </g>
          <g id="line-1">
            <rect
              id="line-1-dash-2"
              fill="#CFD4D7"
              opacity="0.5"
              x="140"
              y="0"
              width="70"
              height="10"
              rx="5"
            />
            <rect
              id="line-1-dash-1"
              fill={color}
              x="0"
              y="0"
              width="130"
              height="10"
              rx="5"
            />
          </g>
        </g>
      </g>
    </g>
  </svg>
);

export default Svg;
